import { POI } from '../data';

/**
 * Generates a KML file from an array of POIs for import into Google My Maps.
 */
export function generateKML(pois: POI[], dayLabel: string): string {
  const placemarks = pois
    .filter(p => p.location)
    .map(p => `
    <Placemark>
      <name>${escapeXml(p.title.en)}</name>
      <description>${escapeXml(p.description?.en || '')}</description>
      <ExtendedData>
        <Data name="Category"><value>${p.category}</value></Data>
        <Data name="Duration"><value>${p.duration} min</value></Data>
        ${p.priceInEuro ? `<Data name="Price"><value>${p.priceInEuro}</value></Data>` : ''}
        ${p.address ? `<Data name="Address"><value>${escapeXml(p.address)}</value></Data>` : ''}
      </ExtendedData>
      <Point>
        <coordinates>${p.location!.lng},${p.location!.lat},0</coordinates>
      </Point>
    </Placemark>`).join('\n');

  // Also generate a route line if there are 2+ points
  const routeLine = pois.filter(p => p.location).length >= 2
    ? `
    <Placemark>
      <name>Route - ${escapeXml(dayLabel)}</name>
      <Style>
        <LineStyle>
          <color>ff00b410</color>
          <width>3</width>
        </LineStyle>
      </Style>
      <LineString>
        <coordinates>
          ${pois.filter(p => p.location).map(p => `${p.location!.lng},${p.location!.lat},0`).join('\n          ')}
        </coordinates>
      </LineString>
    </Placemark>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Expedition Plan - ${escapeXml(dayLabel)}</name>
    <description>Generated by Expedition Planner</description>
    <Style id="sightseeing">
      <IconStyle><color>ff00aaff</color></IconStyle>
    </Style>
    <Style id="activity">
      <IconStyle><color>ff00ff00</color></IconStyle>
    </Style>
    <Style id="food">
      <IconStyle><color>ff00ccff</color></IconStyle>
    </Style>
    ${placemarks}
    ${routeLine}
  </Document>
</kml>`;
}

/**
 * Triggers a browser download of a KML file.
 */
export function downloadKML(pois: POI[], dayLabel: string) {
  const kml = generateKML(pois, dayLabel);
  const blob = new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `itinerary-${dayLabel.replace(/\s+/g, '-').toLowerCase()}.kml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a Google Maps directions URL with multiple waypoints.
 */
export function generateGoogleMapsDirectionsUrl(pois: POI[]): string | null {
  const located = pois.filter(p => p.location);
  if (located.length < 2) return null;

  const origin = `${located[0].location!.lat},${located[0].location!.lng}`;
  const destination = `${located[located.length - 1].location!.lat},${located[located.length - 1].location!.lng}`;
  const waypoints = located.slice(1, -1).map(p => `${p.location!.lat},${p.location!.lng}`).join('|');

  let url = `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=driving`;
  if (waypoints) url += `&waypoints=${waypoints}`;
  return url;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
